/* Synthèses originales de référence. Aucune catégorie n'est calculée automatiquement.
 * Mettre à jour les sources, leur date de revue et les tests lors d'une révision. */
(function (root) {
  const edge = 'https://edge.sitecorecloud.io/americancoldf5f-acrorgf92a-productioncb02-3650/media/ACR/Files/RADS/';
  const acr = 'https://www.acr.org/Clinical-Resources/Clinical-Tools-and-Reference/Reporting-and-Data-Systems/';
  const source = (label, url) => ({label, url});
  const row = (score, title, risk, criteria, action, tone = 'neutral') => ({score, title, risk, criteria, action, tone});
  const section = (title, items) => ({title, items});
  const variant = (id, label, version, population, rows, sections, tips, sources) => ({id, label, version, population, rows, sections, tips, sources});
  const biopsy = 'Prélèvement tissulaire pour diagnostic, avec vérification de la concordance radio-histologique.';
  const biSources = [source('ACR • BI-RADS v2025', acr+'BI-RADS'),source('Catégories mammographie • p. 4',edge+'BI-RADS/BI-RADS-Summary-Form-Mammography.pdf'),source('Nouveautés v2025 • p. 1–10',edge+'BI-RADS/BIRADS-v2025-Whats-New.pdf'),source('CEM • lexique et catégories',edge+'BI-RADS/BI-RADS-Summary-Form-Recombined-Images.pdf')];
  const biRows = [
    row('0','Incomplet — imagerie complémentaire','Non attribuable','Le bilan nécessite des acquisitions ou examens complémentaires.','Compléter le bilan avant une catégorie définitive.'),
    row('0','Incomplet — antériorités nécessaires','Non attribuable','La comparaison aux examens précédents est nécessaire.','Récupérer les antériorités puis conclure.'),
    row('1','Négatif','Pratiquement 0 %','Pas d’anomalie identifiée.','Dépistage habituel adapté au terrain et au programme local.','low'),
    row('2','Bénin','Pratiquement 0 %','Constatation caractérisée comme bénigne.','Dépistage habituel ; prendre en compte une éventuelle discordance clinique.','low'),
    row('3','Probablement bénin','> 0 à ≤ 2 %','Aspect probablement bénin après bilan approprié.','Surveillance rapprochée, habituellement premier contrôle à 6 mois, selon modalité et évolution.','watch'),
    row('4','Suspect','> 2 à < 95 %','Anomalie justifiant un diagnostic tissulaire. Sous-catégories ci-dessous pour mammographie/échographie.','Diagnostic tissulaire recommandé.','high'),
    row('4A','Faible suspicion','> 2 à ≤ 10 %','Sous-catégorie de suspicion faible. Mammographie/échographie.',biopsy,'watch'),
    row('4B','Suspicion intermédiaire','> 10 à ≤ 50 %','Sous-catégorie de suspicion intermédiaire. Mammographie/échographie.',biopsy,'high'),
    row('4C','Forte suspicion','> 50 à < 95 %','Sous-catégorie de suspicion forte, sans atteindre la catégorie 5.',biopsy,'high'),
    row('5','Très évocateur de malignité','≥ 95 %','Constatations très suspectes.',biopsy,'critical'),
    row('6','Malignité prouvée','Diagnostic histologique connu','Cancer déjà confirmé par prélèvement.','Suivi chirurgien/oncologue ; traitement local définitif lorsque indiqué.','critical')
  ];
  const biSections = [section('Ce qui change en v2025', ['Le CEM devient une section intégrée du manuel. La catégorie 0 distingue explicitement complément d’imagerie et comparaison aux antériorités.','Le compte rendu précise indication, modalité, localisation, conclusion et recommandation. Le présent guide ne reproduit pas l’atlas ni ses images.']),section('CEM • lecture combinée',['Les images de basse énergie utilisent le lexique mammographique. Les images recombinées décrivent rehaussement de fond, masses, rehaussement non masse et asymétrie rehaussée.','Décrire visibilité relative au fond, forme, contours, distribution et homogénéité du rehaussement. Ne pas transposer les sous-catégories 4A–4C au CEM ou à l’IRM.'])];
  const piSources = [source('ACR–ESUR–AdMeTech • PI-RADS v2.1',edge+'PI-RADS/PIRADS-2019.pdf'),source('EAU • décisions de biopsie et densité du PSA', 'https://uroweb.org/guidelines/prostatecancer/chapter/diagnostic-evaluation')];
  const piActionLow = 'Avis urologique selon suspicion clinique. EAU : une surveillance du PSA peut remplacer la biopsie si IRM négative, densité < 0,20 ng/mL/cm³ et absence d’antécédent familial, dans un contexte de faible suspicion (recommandation faible).';
  const piRows = [
    row('1','Très faible probabilité','Cancer cliniquement significatif très improbable','Pas de signe suspect ; en zone transitionnelle, nodule typique totalement encapsulé possible.',piActionLow,'low'),
    row('2','Faible probabilité','Cancer significatif improbable','Aspect peu suspect selon la séquence dominante et les règles de combinaison.',piActionLow,'low'),
    row('3','Équivoque','Probabilité indéterminée','Zone périphérique : DWI 3, DCE négatif. Zone transitionnelle : T2 2 + DWI ≥ 4, ou T2 3 + DWI ≤ 4.','EAU : si densité < 0,10 et absence d’antécédent familial avec très faible suspicion, surveillance PSA envisageable ; sinon discuter biopsies ciblées et périlésionnelles.','watch'),
    row('4','Probabilité élevée','Cancer significatif probable','DWI 4 en zone périphérique, ou DWI 3 + DCE positif ; en zone transitionnelle T2 4, ou T2 3 + DWI 5.','Avis urologique pour biopsies ciblées et prélèvements périlésionnels selon le contexte.','high'),
    row('5','Probabilité très élevée','Cancer significatif très probable','Critères de score 4 sur la séquence dominante avec diamètre ≥ 15 mm ou extension extraprostatique/invasion certaine.','Avis urologique pour confirmation histologique ciblée et évaluation de l’extension.','critical')
  ];
  const piSections = [section('Séquence dominante', ['Zone périphérique : diffusion (DWI et ADC). Seul DWI 3 est reclassé en 4 par un DCE positif.','Zone transitionnelle : T2. T2 1 reste 1 ; T2 2 devient 3 si DWI ≥ 4 ; T2 3 devient 4 si DWI 5 ; T2 4/5 reste 4/5.']),section('Repères de lecture',['DWI 3 : anomalie focale ADC ou haut b, éventuellement marquée sur une seule composante. DWI 4 : baisse ADC ET hausse du signal haut b marquées, foyer < 15 mm.','T2 transitionnel 4 : foyer lenticulaire ou non circonscrit, homogène, modérément hypointense et < 15 mm.','DCE positif : rehaussement focal précoce ou contemporain du tissu adjacent, concordant avec une anomalie suspecte T2/DWI.']),section('Densité du PSA • information indépendante',['PSA sérique (ng/mL) ÷ volume prostatique (cm³ ou mL). La densité ne modifie jamais le score PI-RADS.','Les décisions EAU dépendent aussi des antécédents, de la qualité de l’IRM et du contexte de biopsie. Aucun seuil isolé n’exclut un cancer.'])];
  const liSources = [source('ACR • diagnostic CT/MRI v2018',edge+'LI-RADS/LI-RADS-CT-MRI-2018-Core.pdf'),source('ACR • bibliothèque LI-RADS',acr+'LI-RADS')];
  const liRows = [
    row('LR-NC','Non catégorisable','Non évaluable','Qualité ou phases insuffisantes.','Répéter ou changer d’imagerie diagnostique, habituellement sous 3 mois.'),
    row('LR-1','Certainement bénin','Bénin','Aspect diagnostique de bénignité.','Poursuivre la surveillance habituelle du terrain à risque, généralement à 6 mois.','low'),
    row('LR-2','Probablement bénin','Faible suspicion de CHC','Aspect probablement bénin sans certitude.','Surveillance à 6 mois ; envisager répétition diagnostique dans les 6 mois selon le cas.','low'),
    row('LR-3','Probabilité intermédiaire','CHC indéterminé','Combinaison taille/critères ne permettant pas LR-4 ou LR-5.','Scanner/IRM de contrôle ou modalité alternative à 3–6 mois.','watch'),
    row('LR-4','Probablement CHC','Forte suspicion de CHC','Critères majeurs insuffisants pour LR-5.','Discussion multidisciplinaire : contrôle rapproché, souvent sous 3 mois, ou biopsie selon impact thérapeutique.','high'),
    row('LR-5','Certainement CHC','CHC sur critères d’imagerie','Population éligible, taille ≥ 10 mm et combinaison requise des critères majeurs.','Bilan d’extension et prise en charge en réunion multidisciplinaire ; biopsie non systématiquement requise.','critical'),
    row('LR-M','Malignité non spécifique du CHC','Malin probable ou certain','Aspect en cible ou autres signes de malignité non spécifiques du CHC.','Discussion multidisciplinaire, souvent avec biopsie pour préciser le type tumoral.','critical'),
    row('LR-TIV','Tumeur dans une veine','Invasion tumorale veineuse','Tissu tumoral rehaussé dans une veine ; ne préjuge pas à lui seul du type tumoral.','Discussion multidisciplinaire et bilan d’extension ; biopsie selon contexte.','critical')
  ];
  const liSections = [section('Critères majeurs • scanner/IRM',['Hyperrehaussement artériel non périphérique, washout non périphérique, capsule rehaussée, taille et croissance seuil : ≥ 50 % en ≤ 6 mois.','LR-5 : 10–19 mm avec hyperrehaussement artériel non périphérique et washout ou croissance seuil ; ≥ 20 mm avec cet hyperrehaussement et au moins un autre critère majeur. Une capsule seule pour 10–19 mm ne suffit pas.','Les signes auxiliaires peuvent ajuster la catégorie, mais ne permettent pas de passer en LR-5. Consulter la matrice complète pour les autres combinaisons.'])];
  const traRows = (radiation) => [
    row('LR-TR Nonevaluable','Non évaluable','Viabilité indéterminable','Technique insuffisante pour juger le rehaussement.','Nouvelle imagerie adaptée, généralement dans les 3 mois.'),
    row('LR-TR Nonviable','Non viable en imagerie','Pas de signe de viabilité macroscopique','Absence de rehaussement de type masse dans ou au bord de la zone traitée.','Surveillance post-thérapeutique scanner/IRM, généralement vers 3 mois.','low'),
    radiation ? row('LR-TR Nonprogressing','Sans progression','Réponse en évolution','Rehaussement de type masse stable ou diminuant après irradiation.','Contrôle scanner/IRM vers 3 mois ; discussion multidisciplinaire si situation complexe.','watch') : row('LR-TR Equivocal','Équivoque','Viabilité incertaine','Doute sur la présence d’un rehaussement de type masse.','Contrôle vers 3 mois, même technique ou alternative ; discussion multidisciplinaire si nécessaire.','watch'),
    row('LR-TR Viable','Viable','Forte probabilité de tissu tumoral viable', radiation ? 'Rehaussement de type masse nouveau ou augmentant après irradiation.' : 'Rehaussement de type masse dans ou au bord de la zone traitée, quelle que soit la phase.','Réunion multidisciplinaire pour adaptation thérapeutique, souvent retraitement.','critical')
  ];
  const lungRows = [
    row('0','Incomplet','Non attribuable','Antériorités manquantes, exploration incomplète ou contexte infectieux/inflammatoire indéterminé.','Comparaison ou complément ; si suspicion infectieuse/inflammatoire, scanner faible dose à 1–3 mois.'),
    row('1','Négatif','Pas de nodule suspect','Absence de nodule ou nodule contenant graisse/calcifications typiquement bénignes.','Dépistage par scanner faible dose à 12 mois.','low'),
    row('2','Bénin / comportement indolent','Faible suspicion','Solide initial < 6 mm ou nouveau < 4 mm ; partiellement solide initial < 6 mm au total ; verre dépoli pur < 30 mm, ou ≥ 30 mm stable/à croissance lente.','Scanner faible dose à 12 mois.','low'),
    row('3','Probablement bénin','Faible suspicion à surveiller','Solide initial 6–<8 mm ou nouveau 4–<6 mm ; partiellement solide initial ≥ 6 mm avec composante solide < 6 mm, ou nouveau < 6 mm au total ; verre dépoli ≥ 30 mm initial/nouveau.','Scanner faible dose à 6 mois.','watch'),
    row('4A','Suspect','Suspicion accrue','Solide initial 8–<15 mm, croissant < 8 mm, ou nouveau 6–<8 mm ; partiellement solide initial ≥ 6 mm avec partie solide 6–<8 mm, ou partie solide nouvelle/croissante < 4 mm.','Scanner faible dose à 3 mois ; TEP-TDM envisageable si composante solide ≥ 8 mm.','high'),
    row('4B','Très suspect','Forte suspicion','Solide initial ≥ 15 mm ou nouveau/croissant ≥ 8 mm ; composante solide initiale ≥ 8 mm ou nouvelle/croissante ≥ 4 mm. Une croissance lente répétée d’un solide/partiellement solide peut relever de 4B.','Scanner diagnostique, avis spécialisé et/ou prélèvement ; TEP-TDM si composante solide ≥ 8 mm, selon probabilité, état clinique et préférences.','critical'),
    row('4X','Suspicion additionnelle','Forte suspicion','Nodule de catégorie 3 ou 4 avec signes supplémentaires suspects, par exemple spiculation ou adénopathies.','Bilan diagnostique spécialisé adapté, comme pour une anomalie très suspecte.','critical'),
    row('S','Modificateur extra-oncologique','Dépend de la découverte','Anomalie cliniquement significative autre que le cancer pulmonaire ; s’ajoute à la catégorie.','Prise en charge propre à la découverte ; ne remplace pas la catégorie nodulaire.')
  ];
  const lungSections = [section('Croissance et suivi',['Croissance : augmentation du diamètre moyen > 1,5 mm sur 12 mois. Franchir un seuil de taille peut changer la catégorie même sans cette croissance.','Après 4A stable/diminué à 3 mois : catégorie 3 (hors nodule bronchique), puis 2 si stabilité/diminution au contrôle à 6 mois.','Verre dépoli : l’apparition d’une composante solide impose la grille des nodules partiellement solides.']),section('Bronches, plèvre et kystes',['Juxtapleural : solide lisse, ovale/lenticulaire/triangulaire < 10 mm → 2. Nodule bronchique sous-segmentaire → généralement 2 ; segmentaire ou plus proximal initial → 4A, persistant/croissant → 4B.','Kyste à paroi épaisse (≥ 2 mm) ou multiloculaire initial → 4A ; augmentation de la paroi/nodularité, de la multilocularité ou des opacités → 4B. Croissance de la seule composante kystique d’un kyste à paroi épaisse → 3.'])];
  const tiRows = [
    row('TR1','Bénin','Bénin','0 point ; notamment kyste pur ou nodule spongiforme typique.','Pas de cytoponction ni de suivi échographique selon ACR TI-RADS.','low'),
    row('TR2','Non suspect','Très faible suspicion','2 points.','Pas de cytoponction ni de suivi selon ACR TI-RADS.','low'),
    row('TR3','Faiblement suspect','Faible suspicion','3 points.','Cytoponction si ≥ 25 mm ; suivi si ≥ 15 mm à 1, 3 et 5 ans. En dessous : pas de suivi systématique.','watch'),
    row('TR4','Modérément suspect','Suspicion modérée','4 à 6 points.','Cytoponction si ≥ 15 mm ; suivi si ≥ 10 mm à 1, 2, 3 et 5 ans. En dessous : pas de suivi systématique.','high'),
    row('TR5','Très suspect','Forte suspicion','≥ 7 points.','Cytoponction si ≥ 10 mm ; suivi si ≥ 5 mm chaque année pendant 5 ans. En dessous : pas de suivi systématique.','critical')
  ];
  const tiSections = [section('Les cinq familles de critères',['Composition : kystique/spongiforme 0 ; mixte 1 ; solide/quasi solide 2. Un kyste pur ou spongiforme typique est TR1 sans additionner les autres familles.','Échogénicité : anéchogène 0 ; iso/hyperéchogène 1 ; hypoéchogène 2 ; très hypoéchogène 3.','Forme transverse : plus large que haut 0 ; plus haut que large 3.','Contours : lisses/mal définis 0 ; lobulés/irréguliers 2 ; extension extrathyroïdienne 3.','Foyers échogènes (cumulables) : aucun/grandes queues de comète 0 ; macrocalcifications 1 ; calcifications périphériques 2 ; foyers ponctués 3.']),section('Conditions de suivi',['Les seuils concernent le plus grand diamètre. Si le seuil de cytoponction est atteint, cette option prime sur la simple surveillance.','Croissance significative : ≥ 20 % dans au moins deux dimensions avec ≥ 2 mm, ou ≥ 50 % du volume. Réévaluer selon nouvelle taille et catégorie.'])];
  const cadRows = [
    row('0','Absence de coronaropathie','Pas de plaque ni sténose','0 % et absence de plaque.','Rechercher une autre cause aux symptômes ; prise en charge des facteurs de risque selon le contexte.','low'),
    row('1','Atteinte minime','Non obstructive','Sténose 1–24 %, ou plaque sans sténose.','Prévention adaptée à la charge de plaque et au risque global.','low'),
    row('2','Atteinte légère','Non obstructive','Sténose 25–49 %.','Prévention et contrôle des facteurs de risque ; considérer les autres causes de symptômes.','watch'),
    row('3','Atteinte modérée','Obstruction possible','Sténose 50–69 %.','Selon symptômes : évaluation fonctionnelle (FFR-CT, perfusion ou test de stress) et avis cardiologique ; traitement préventif/antiangineux adapté.','watch'),
    row('4A','Atteinte sévère','Obstructive','Sténose 70–99 % dans un ou deux vaisseaux.','Avis cardiologique : coronarographie invasive ou évaluation fonctionnelle selon symptômes, anatomie et ischémie.','high'),
    row('4B','Anatomie à haut risque','Obstructive sévère','Tronc commun ≥ 50 % ou sténoses ≥ 70 % des trois vaisseaux.','Avis cardiologique et coronarographie invasive généralement recommandée.','critical'),
    row('5','Occlusion','Occlusion complète','100 % dans au moins un vaisseau.','Avis cardiologique ; distinguer occlusion aiguë et chronique, discuter exploration invasive/revascularisation.','critical'),
    row('N','Non diagnostique','Atteinte obstructive non exclue','Segment non interprétable empêchant une conclusion fiable.','Compléter l’exploration. Si sténose ≥ 50 % ailleurs, conserver sa catégorie et ajouter N.')
  ];
  const cadSections = [section('P • charge de plaque globale',['P1 faible, P2 modérée, P3 importante, P4 extensive. Indiquer la méthode : score calcique, nombre de segments atteints (SIS) ou estimation visuelle.','Repères CAC : 1–100 / 101–300 / 301–999 / ≥ 1000. Repères SIS : 1–2 / 3–4 / 5–7 / ≥ 8. Une absence de calcium n’exclut pas la plaque non calcifiée.','Ne pas ajouter P0 à CAD-RADS 0. La charge de plaque est indépendante du degré maximal de sténose.']),section('I • ischémie, uniquement si étudiée',['FFR-CT lésionnelle : I+ si ≤ 0,75 ; I− si > 0,80 ; I+/− entre les deux. Interpréter en aval de la lésion, avec qualité technique et contexte.','La perfusion de stress peut également documenter I+ ou I−. Une sténose anatomique seule ne permet pas d’ajouter I+.']),section('Autres modificateurs',['N : segment non diagnostique ; HRP : plaque à haut risque (au moins deux caractéristiques) ; S : stent ; G : pontage ; E : anomalie non athéroscléreuse.','HRP : remodelage positif, faible atténuation < 30 UH, calcification ponctuée et signe de l’anneau.']),section('Douleur stable ou aiguë',['Les conduites ci-dessus sont des repères pour la douleur stable. En douleur aiguë, intégrer ECG, troponines et état clinique : une suspicion de syndrome coronarien aigu impose la filière urgente, sans attendre ce score.','Les catégories 4B/5 en contexte aigu motivent une prise en charge hospitalière cardiologique ; aucun score ne remplace l’évaluation clinique.'])];
  const usRows = [
    row('0','Évaluation incomplète','Non attribuable','Caractérisation limitée par des facteurs techniques.','Compléter par échographie ou IRM.'),
    row('1','Ovaire normal','Sans lésion pathologique','Ovaire normal ou constatation physiologique, follicule/corps jaune habituellement ≤ 3 cm avant ménopause.','Pas de suivi spécifique.','low'),
    row('2','Quasi certainement bénin','< 1 %','Kyste simple < 10 cm ; certains kystes lisses uni/biloculaires ou lésions bénignes typiques.','Selon morphologie, taille et ménopause : voir repères détaillés ci-dessous. Pas de délai unique pour toute la catégorie 2.','low'),
    row('3','Faible risque','1 à < 10 %','Exemples : kyste lisse uni/biloculaire ≥ 10 cm ; multiloculaire lisse < 10 cm avec Doppler < 4 ; solide lisse sans flux ou avec ombre et Doppler 2–3.','Gynécologue ; si non opéré, échographie dans les 6 mois. Si solide : expertise échographique ou IRM.','watch'),
    row('4','Risque intermédiaire','10 à < 50 %','Exemples : kyste uniloculaire avec 1–3 papilles ; bi/multiloculaire avec solide et Doppler 1–2 ; solide lisse sans ombre et Doppler 2–3.','Échographie experte/IRM ; gynécologue avec avis oncogynécologique, ou oncogynécologue directement.','high'),
    row('5','Risque élevé','≥ 50 %','≥ 4 papilles ; bi/multiloculaire avec solide et Doppler 3–4 ; solide irrégulier ou très vascularisé ; nodules péritonéaux/ascite inexpliquée.','Orientation en oncogynécologie et bilan selon cette équipe.','critical')
  ];
  const usSections = [section('Catégorie 2 • repères de surveillance',['Kyste simple : avant ménopause, ≤ 5 cm sans suivi, > 5 et < 10 cm contrôle à 12 mois ; après ménopause, ≤ 3 cm sans suivi, > 3 et < 10 cm contrôle à 12 mois.','Kyste lisse non simple uniloculaire ou biloculaire : > 3 et < 10 cm, contrôle à 6 mois ; ≤ 3 cm sans suivi avant ménopause, contrôle à 12 mois après.','Kyste hémorragique typique avant ménopause : ≤ 5 cm sans suivi, > 5 et < 10 cm contrôle à 2–3 mois. Après ménopause tardive, reclasser selon la morphologie.','Dermoïde typique < 10 cm non opéré : surveillance généralement à 12 mois (facultative si ≤ 3 cm). Endométriome typique < 10 cm : suivi à 12 mois avant ménopause ; après ménopause, confirmer par contrôle à 2–3 mois, expertise ou IRM.']),section('Lexique à distinguer',['Biloculaire = deux logettes ; multiloculaire = au moins trois. Une papille est une composante solide ≥ 3 mm entourée de liquide sur trois côtés.','Doppler : score couleur 1 absent, 2 faible, 3 modéré, 4 très intense. Réévaluer toute modification morphologique.','Les délais supposent un risque clinique moyen et l’absence de symptômes aigus. Une torsion suspectée relève de l’urgence, quel que soit le score.'])];
  const mriRows = [
    row('0','Évaluation incomplète','Non attribuable','Examen ne permettant pas une caractérisation adéquate.','Compléter l’examen ou demander une expertise.'),
    row('1','Ovaire normal','Sans lésion pathologique','Absence de lésion ; follicule, kyste hémorragique ou corps jaune ≤ 3 cm avant ménopause.','Pas de suivi spécifique de constatation physiologique.','low'),
    row('2','Quasi certainement bénin','VPP < 0,5 %','Exemples : kyste simple/endométriosique sans tissu solide rehaussé ; tissu uniformément sombre en T2 ET DWI ; lésion lipidique typique.','Adapter au contexte gynécologique ; aucun calendrier universel de suivi IRM n’est établi dans la grille de risque.','low'),
    row('3','Faible risque','VPP ≈ 5 %','Kyste multiloculaire à cloisons/paroi lisses sans tissu solide rehaussé ; ou tissu solide avec courbe dynamique à faible risque.','Discussion gynécologique individualisée ; surveillance ou traitement selon symptômes et caractéristiques.','watch'),
    row('4','Risque intermédiaire','VPP ≈ 50 %','Tissu solide à courbe intermédiaire ; sans dynamique, rehaussement ≤ myomètre à 30–40 s ; ou lésion lipidique avec volumineux tissu solide rehaussé.','Avis spécialisé gynécologique/oncogynécologique ; décision multidisciplinaire.','high'),
    row('5','Risque élevé','VPP ≈ 90 %','Tissu solide à courbe à haut risque ; sans dynamique, rehaussement > myomètre à 30–40 s ; ou dépôts péritonéaux/épiploïques.','Orientation oncogynécologique pour bilan et prise en charge.','critical')
  ];
  const mriSections = [section('IRM • précautions d’interprétation',['Les VPP sont celles de la catégorie dans son ensemble, incluant tumeurs borderline et cancers invasifs. Elles ne sont pas la probabilité individuelle d’un signe isolé.','Un caillot non rehaussé n’est pas du tissu solide. Le critère « sombre T2/sombre DWI » doit être homogène.','Courbe faible : montée progressive sans plateau ; intermédiaire : montée initiale ≤ myomètre avec plateau ; élevée : montée initiale > myomètre avec plateau. Préférer une dynamique à résolution temporelle ≤ 15 s.','Un petit nodule de Rokitansky faiblement rehaussé dans un tératome typique ne suffit pas à classer 4.']),section('Conduite à tenir • limite de la source',['La grille ACR IRM de 2024 décrit le risque, sans imposer de calendrier universel ni de traitement pour chaque catégorie. Les orientations ci-dessus sont des repères de discussion clinique, non des prescriptions ACR de suivi.'])];
  const viSources = [source('Panebianco et al. • développement original VI-RADS, Eur Urol 2018','https://pubmed.ncbi.nlm.nih.gov/29755006/'),source('VI-RADS • article de consensus et critères','https://pmc.ncbi.nlm.nih.gov/articles/PMC6690492/'),source('Radiology Assistant • sémiologie VI-RADS','https://radiologyassistant.nl/abdomen/bladder/bladder-cancer-vi-rads'),source('EAU • diagnostic des tumeurs vésicales','https://uroweb.org/guidelines/non-muscle-invasive-bladder-cancer/chapter/diagnosis'),source('Urofrance • recommandations TVNIM 2024–2026','https://www.urofrance.org/recommandation/recommandations-francaises-du-comite-de-cancerologie-de-lafu-actualisation-2024-2026-tumeurs-de-la-vessie-ninfiltrant-pas-le-muscle-tvnim/')];
  const viRows = [
    row('1','Invasion musculaire très improbable','Très faible probabilité de muscle invasif','T2 : ligne continue en hyposignal de la muscularis propria, lésion < 1 cm, pédicule possible. DCE : rehaussement précoce de la couche interne sans atteinte musculaire. DWI : ligne musculaire continue, signal intermédiaire.','Décrire précisément la lésion et organiser la prise en charge urologique ; VI-RADS 1 ne remplace ni la RTUV ni l’histologie.','low'),
    row('2','Invasion musculaire improbable','Faible probabilité de muscle invasif','T2 : ligne musculaire continue, lésion > 1 cm ; tumeur papillaire avec pédicule ou couche interne épaissie, ou tumeur sessile avec couche interne épaissie. DCE/DWI : muscularis propria respectée.','Confronter à la cystoscopie et à l’histologie ; la stratégie de RTUV et la seconde résection dépendent du grade, du stade et du contexte urologique.','low'),
    row('3','Équivoque','Probabilité indéterminée','T2 : disparition du pédicule ou de la couche interne épaissie, mais ligne musculaire en hyposignal continue. DCE/DWI : absence des critères de catégorie 2, sans rupture musculaire claire.','Ne pas conclure à l’absence d’invasion. Discussion urologique et corrélation à la RTUV/histologie ; prudence après inflammation ou geste récent.','watch'),
    row('4','Invasion musculaire probable','Forte probabilité de muscle invasif','T2 : interruption de la ligne musculaire. DCE : extension focale du rehaussement précoce dans la muscularis propria. DWI : hypersignal tumoral avec hyposignal ADC, extension focale au muscle.','Bilan et avis uro-oncologique pour tumeur potentiellement infiltrante ; la confirmation repose sur l’histologie et le stade complet.','high'),
    row('5','Invasion musculaire et au-delà très probable','Très forte probabilité','T2 : extension à la graisse périvésicale. DCE : rehaussement précoce dans la graisse extravésicale. DWI : hypersignal et ADC bas traversant la paroi jusqu’à la graisse.','Avis uro-oncologique rapide, stadification et discussion multidisciplinaire ; rechercher extension locale, ganglionnaire et métastatique.','critical')
  ];
  const viSections = [section('Sémiologie IRM par séquence',['T2 est la première séquence à analyser : la muscularis propria normale forme une ligne continue en hyposignal ; l’urine est en hypersignal et la tumeur a un signal intermédiaire.','DCE : la couche interne se rehausse précocement dans les tumeurs non musculaires ; le muscle normal se rehausse plus tard et progressivement. Une extension focale du rehaussement précoce dans le muscle suggère VI-RADS 4, puis dans la graisse VI-RADS 5.','DWI/ADC : la tumeur montre une restriction de diffusion, hypersignal en DWI et hyposignal ADC. La diffusion et le DCE tranchent la plupart des discordances pour les scores 4–5.']),section('Combinaison et discordance',['T2 guide le premier regard, mais une invasion musculaire certaine (VI-RADS 4–5) est déterminée par DWI et DCE. Si T2 est discordant avec DWI, privilégier DWI ; si DWI est sous-optimale, privilégier DCE.','Exemple : T2 4 avec DWI ou DCE 5 → score final 5. T2 5 avec DWI 4 → score final 4.']),section('Anatomie, préparation et pièges',['La paroi comprend la couche interne (urothélium + lamina propria), la muscularis propria/détrusor et la graisse périvésicale. L’œdème inflammatoire peut épaissir et rehausser précocement la couche interne, mimant une tumeur.','Idéalement, réaliser l’IRM avant la RTUV ; décrire nombre, taille, morphologie et localisation (dôme, parois, trigone, col, orifices urétéraux, urètre prostatique).','Dans la graisse périvésicale, T2 peut surestimer l’extension par effet de volume partiel : DCE et DWI aident à distinguer VI-RADS 4 de 5.']),section('Seuils et limites',['Dans les recommandations EAU, VI-RADS ≥ 4 est souvent utilisé pour identifier une probabilité élevée de tumeur infiltrant le muscle, avec des performances variables selon les cohortes. Le seuil ne décide pas seul d’une cystectomie ou d’un traitement.','Le CIS ne peut pas être diagnostiqué par l’imagerie seule. Inflammation, résection récente, instillation intravésicale et sous-distension peuvent créer des faux positifs ou rendre l’examen non fiable.'])];
  const modules = [
    {id:'bi',name:'BI-RADS',organ:'Sein',icon:'ribbon',accent:'rose',subtitle:'Mammographie, échographie, IRM & CEM',full:'Breast Imaging Reporting and Data System',agency:'ACR',variants:[variant('reference','Référence multimodale','v2025','Imagerie mammaire de dépistage ou diagnostique ; appliquer le lexique propre à la modalité.',biRows,biSections,['BI-RADS 0 est provisoire, pas une catégorie de risque.','Une histologie bénigne discordante avec une image suspecte doit être réévaluée.','Les sous-catégories 4A–4C concernent mammographie/échographie. Les détails non présents dans les résumés publics nécessitent le manuel complet.'],biSources)]},
    {id:'pi',name:'PI-RADS',organ:'Prostate',icon:'crosshairs',accent:'blue',subtitle:'IRM prostatique & densité du PSA',full:'Prostate Imaging Reporting and Data System',agency:'ACR · ESUR · AdMeTech',variants:[variant('mri','IRM prostatique','v2.1 · 2019','Suspicion de cancer prostatique cliniquement significatif ; ne pas appliquer tel quel au suivi après traitement.',piRows,piSections,['Inflammation, hémorragie et nodules d’hyperplasie peuvent simuler une lésion.','Documenter une diffusion dégradée ; une séquence inexploitable ne vaut pas un score rassurant.','PI-RADS exprime une probabilité de cancer significatif, pas un stade TNM.'],piSources)]},
    {id:'li',name:'LI-RADS',organ:'Foie',icon:'layer-group',accent:'amber',subtitle:'Diagnostic & réponse thérapeutique',full:'Liver Imaging Reporting and Data System',agency:'ACR',variants:[
      variant('diagnostic','Diagnostic','CT/MRI v2018','Adultes à risque de CHC : cirrhose, hépatite B chronique ou CHC actuel/antérieur. Exclure les cirrhoses vasculaires et la fibrose hépatique congénitale ; non applicable à tout nodule hépatique.',liRows,liSections,['Avec contraste hépatobiliaire, une hypointensité transitionnelle ne suffit pas au washout : utiliser la phase portale pour ce critère avec gadoxétate.','Ne pas attribuer LR-5 à une observation < 10 mm.','LR-M ne signifie pas automatiquement cholangiocarcinome ; LR-TIV n’est pas synonyme de CHC.'],liSources),
      variant('nonradiation','Après traitement sans irradiation','TRA v2024','Lésion de CHC traitée localement sans irradiation (ablation, embolisation…) ou évaluation du bord de résection ; pas d’évaluation globale de traitement systémique.',traRows(false),[section('Algorithme dédié',['Le rehaussement de type masse est central. En IRM, restriction de diffusion ou hypersignal T2 modéré concordant peut permettre de reclasser Equivocal en Viable selon les critères ACR.'])],['Un fin rehaussement périphérique lisse peut être une modification attendue.','Nonviable en imagerie n’exclut pas un résidu microscopique. Une nouvelle lésion hors zone traitée relève de l’algorithme diagnostique.'],[source('ACR • TRA sans irradiation v2024',edge+'LI-RADS/LI-RADS-CTMR-Nonradiation-TRA-v2024-Core.pdf')]),
      variant('radiation','Après irradiation','TRA v2024','Lésion de CHC après radioembolisation (TARE) ou radiothérapie stéréotaxique (SBRT).',traRows(true),[section('Une réponse parfois retardée',['Nonprogressing est propre à l’irradiation. Le rehaussement persistant stable ou décroissant ne signifie pas nécessairement un échec.','Des signes auxiliaires IRM concordants (diffusion/T2) peuvent faire discuter un reclassement en Viable selon le référentiel.'])],['Comparer avec les examens précédents et la date du traitement.','Une augmentation nouvelle du tissu rehaussé doit être discutée ; la réaction parenchymateuse périphérique ne suffit pas.'],[source('ACR • TRA après irradiation v2024',edge+'LI-RADS/LI-RADS-CTMR-Radiation-TRA-v2024-Core.pdf')])]},
    {id:'lung',name:'Lung-RADS',organ:'Poumon',icon:'lungs',accent:'teal',subtitle:'Scanner thoracique de dépistage',full:'Lung CT Screening Reporting and Data System',agency:'ACR',variants:[variant('screening','Dépistage','v2022','Dépistage du cancer pulmonaire par scanner faible dose. Ne pas substituer Lung-RADS aux recommandations sur les nodules fortuits.',lungRows,lungSections,['Classer selon l’anomalie la plus suspecte. Les délais partent de l’examen actuel.','Les pourcentages de prévalence des catégories ne sont pas des probabilités individuelles de malignité.','Une TEP négative n’exclut pas une tumeur à croissance lente.'],[source('ACR • Lung-RADS v2022',edge+'Lung-RADS/Lung-RADS-2022.pdf'),source('ACR • changements v2022',acr+'Lung-RADS')])]},
    {id:'ti',name:'TI-RADS',organ:'Thyroïde',icon:'diamond',accent:'violet',subtitle:'Échographie & seuils de cytoponction',full:'Thyroid Imaging Reporting and Data System',agency:'ACR',variants:[variant('us','Échographie','ACR · 2017','Nodules thyroïdiens de l’adulte. Les seuils ne remplacent pas le contexte : adénopathie suspecte, fixation TEP, symptômes ou antécédent de cytologie.',tiRows,tiSections,['Ne pas confondre ACR TI-RADS et EU-TIRADS.','Un contour mal défini n’est pas un contour irrégulier. Additionner les types de foyers échogènes présents.','Une catégorie élevée n’entraîne pas automatiquement une cytoponction sous le seuil de taille ; une situation clinique particulière peut modifier la conduite.'],[source('ACR • tableau de points',edge+'TI-RADS/TI-RADS-Assessment-Categories.pdf'),source('ACR • catégories et seuils',edge+'TI-RADS/TI-RADS-Assessment-Categories-Alternative-chart.pdf'),source('ACR • FAQ et suivi','https://radssupport.acr.org/support/solutions/articles/11000071474-acr-ti-rads-faq'),source('ACR • atlas',edge+'TI-RADS/TI-RADS-Atlas.pdf')])]},
    {id:'cad',name:'CAD-RADS',organ:'Coronaires',icon:'heart-pulse',accent:'rose',subtitle:'Sténose, plaque & ischémie',full:'Coronary Artery Disease Reporting and Data System',agency:'SCCT · ACC · ACR · NASCI',variants:[variant('cta','Coroscanner','2.0 · 2022','Coronarographie par scanner ; interprétation par patient selon la sténose maximale et les segments analysables.',cadRows,cadSections,['Une plaque non calcifiée peut exister avec un score calcique nul.','Ne pas déduire l’ischémie du pourcentage de sténose.','Signaler les segments non analysables ; l’occlusion chronique n’équivaut pas à une urgence aiguë.'],[source('Consensus multisociétés • texte intégral','https://pmc.ncbi.nlm.nih.gov/articles/PMC9627235/'),source('Consensus SCCT • JCCT','https://www.journalofcardiovascularct.com/article/S1934-5925(22)00240-4/fulltext')])]},
    {id:'o',name:'O-RADS',organ:'Ovaires & annexes',icon:'circle-nodes',accent:'violet',subtitle:'Deux référentiels : échographie & IRM',full:'Ovarian-Adnexal Reporting and Data System',agency:'ACR',variants:[
      variant('us','Échographie','US v2022','Masses ovariennes/annexielles. Recommandations de prise en charge pour risque moyen sans symptômes aigus ; intégrer statut ménopausique.',usRows,usSections,['Les règles de surveillance ne s’appliquent pas sans adaptation aux symptômes aigus ou au haut risque génétique.','Un caillot n’est pas une végétation vascularisée.','Une lésion dite typique perd ce statut si elle acquiert des caractéristiques atypiques.'],[source('ACR • US v2022, catégories et lésions classiques',edge+'O-RADS/O-RADS--Ultrasound-v2022-Assessment-Categories.pdf'),source('ACR • O-RADS',acr+'O-RADS')]),
      variant('mri','IRM','IRM · documents 2024','Caractérisation IRM des lésions annexielles, notamment indéterminées en échographie ; exclure les origines non annexielles.',mriRows,mriSections,['Ne pas transposer les pourcentages ni les délais échographiques à l’IRM.','Une IRM sans dynamique perd en précision ; documenter cette limite.','Les intervalles et traitements ne sont pas standardisés par la seule grille IRM.'],[source('ACR • grille IRM 2024',edge+'O-RADS/O-RADS-MRI-Risk-Score-Assessment.pdf'),source('ACR • ressources IRM',acr+'O-RADS/MRI')])
    ]},
    {id:'vi',name:'VI-RADS',organ:'Vessie',icon:'bladder',accent:'blue',subtitle:'IRM multiparamétrique & invasion musculaire',full:'Vesical Imaging-Reporting and Data System',agency:'Consensus international · EAU',variants:[variant('mri','IRM vésicale','VI-RADS · 2018','Stadification locale d’une tumeur urothéliale vésicale suspectée ou confirmée, idéalement avant la RTUV. Le score estime l’invasion du détrusor ; il ne remplace ni la cystoscopie ni l’histologie.',viRows,viSections,['Une RTUV récente, une inflammation ou une vessie sous-distendue peuvent mimer une rupture musculaire.','Une catégorie 3 est indéterminée et ne doit pas être interprétée comme une absence d’invasion.','La cartographie lésionnelle et le contexte de traitement sont indispensables au compte rendu.'],viSources)]}
  ];
  // Identifiants immuables : indispensables aux favoris, aux liens et aux brouillons.
  modules.forEach(m => m.variants.forEach(v => {v.reviewed='2026-09-23'; v.rows.forEach((r,i)=>r.id=m.id+'-'+v.id+'-'+i);}));
  root.RADS = {modules, reviewed:'2026-09-23', edition:'1.0.0'};
})(globalThis);
